spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
#        url: jdbc:mysql://192.168.220.1/diancan?characterEncoding=utf-8&useSSL=false
        url: jdbc:mysql://localhost:3306/diancan?useSSL=false&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&serverTimezone=UTC
    jpa:
        show-sql: true

#        database-platform: org.hibernate.dialect.MySQL5Dialect





